### ISSUE TITLE
Exception during test on iPhone 6

### ISSUE THREAD

**Issue by Goldstrike** [Microsoft/ConferenceVision#11]
Hello,

I'm not able to launch the app on my iPhone 6 from Visual Studio or from your [website](https://aka.ms/iosmovai).

On Visual Studio I can see that there is an exception in `AppDelegate `at:
`CrossImageClassifier.Current.Init("VisionModel", ModelType.General);`

The exception is the following:

> Xam.Plugins.OnDeviceCustomVision.ImageClassifierException: Failed to load the model - check the inner exception for more details

If I deploy the app on a simulator, there is no problem.

_**Would you have an explanation?**_

**Comment by davidortinau** [comment]
I need more details to know what is going on here. VisionModel is in the Resources directory of the iOS project. If it's present, then confirm it's a "BundleResource". I wonder if there's a minimum SDK version issue.

If you're still hitting this issue and interested in troubleshooting it, let me know the iOS version number and reopen the issue.
