### ISSUE TITLE
Share image android

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Microsoft/ConferenceVision#12]
How has image sharing been implemented in android? I've been trying to implement for centuries and it never works, is there an example? I checked the code and implemented it, however, without success.

**Comment by davidortinau** [comment]
It uses the native Intent with the share action. This will let the user choose what app or service they prefer to use here.

https://github.com/Microsoft/ConferenceVision/blob/master/ConferenceVision/ConferenceVision.Android/Services/Share.cs#L40

This is based off this article: https://xamarinhelp.com/share-dialog-xamarin-forms/

If you're not having success, check the permissions from Android and make sure your files are stored in a location that permits sharing.

https://developer.android.com/training/sharing/send
